import ATL from '../assets/hawks-logo.svg';
import BOS from '../assets/celtics-logo.svg'
import BKN from '../assets/nets-logo.svg'
import CHA from '../assets/hornets-logo.svg'
import CHI from '../assets/bulls-logo.svg'
import CLE from '../assets/cavaliers-logo.svg'
import DAL from '../assets/mavericks-logo.svg'
import DEN from '../assets/nuggets-logo.svg'
import DET from '../assets/pistons-logo.svg'
import GSW from '../assets/warriors-logo.svg'
import HOU from '../assets/rockets-logo.svg'
import IND from '../assets/pacers-logo.svg'
import LAC from '../assets/clippers-logo.svg'
import LAL from '../assets/lakers-logo.svg'
import MEM from '../assets/grizzlies-logo.svg'
import MIA from '../assets/heat-logo.svg'
import MIL from '../assets/bucks-logo.svg'
import MIN from '../assets/timberwolves-logo.svg'
import NOP from '../assets/pelicans-logo.svg'
import NYK from '../assets/knicks-logo.svg'
import OKC from '../assets/thunder-logo.svg'
import ORL from '../assets/magic-logo.svg'
import PHI from '../assets/76ers-logo.svg'
import PHX from '../assets/suns-logo.svg'
import POR from '../assets/por-logo.svg'
import SAC from '../assets/kings-logo.svg'
import SAS from '../assets/spurs-logo.svg'
import TOR from '../assets/raptors-logo.svg'
import UTA from '../assets/jazz-logo.svg'
import WAS from '../assets/wizards-logo.svg'

const nbaLogos = [ATL, BOS, BKN, CHA, CHI, CLE, DAL, DEN, DET, GSW, HOU, IND, LAC, LAL, MEM, MIA, MIL, MIN, NOP, NYK, OKC, ORL, PHI, PHX, POR, SAC, SAS, TOR, UTA, WAS];

export default nbaLogos;